language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.5.3
  - 2.4.5
  - 2.3.8

os:
  - linux

matrix :
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

gemfile:
  - Gemfile
  - Gemfile-4.x

script: bundle exec rake test

env:
  global:
    - TEST=true

notifications:
  email: false
